/**
 * One-shot: print all text channels and active threads in the configured guild
 * in a format ready to paste into config/channels.yml.
 *
 * Run with:
 *    bun run list-channels
 */
import { ChannelType, type TextChannel } from "discord.js";
import { loginClient, shutdownClient } from "../src/bot/client.ts";
import { loadEnv } from "../src/config.ts";

async function main(): Promise<void> {
  const env = loadEnv();
  const client = await loginClient();

  const guild = await client.guilds.fetch(env.DISCORD_GUILD_ID);
  const allChannels = await guild.channels.fetch();

  // Build a category name map for context
  const categoryNames = new Map<string, string>();
  for (const [id, ch] of allChannels) {
    if (ch?.type === ChannelType.GuildCategory) categoryNames.set(id, ch.name);
  }

  // Filter to text channels, sorted by position
  const textChannels = [...allChannels.values()]
    .filter((ch) => ch?.type === ChannelType.GuildText)
    .sort((a, b) => (a!.position ?? 0) - (b!.position ?? 0)) as TextChannel[];

  console.log(`# Generated by: bun run list-channels`);
  console.log(`# Copy the entries you want into config/channels.yml\n`);
  console.log(`guild_id: "${env.DISCORD_GUILD_ID}"\nchannels:`);

  for (const ch of textChannels) {
    const category = ch.parentId ? (categoryNames.get(ch.parentId) ?? ch.parentId) : null;
    const catComment = category ? `  # category: ${category}` : "";
    console.log(`${catComment}`);
    console.log(`  - id: "${ch.id}"`);
    console.log(`    name: "${ch.name}"`);
    console.log(`    classify: true`);

    // Show active threads as commented-out entries for reference
    try {
      const active = await ch.threads.fetchActive();
      if (active.threads.size > 0) {
        console.log(`    include_threads: false  # set true to also index threads`);
        console.log(`    # active threads (indexed automatically when include_threads: true):`);
        for (const [, t] of active.threads) {
          console.log(`    #   ${t.name}  (id: ${t.id})`);
        }
      }
    } catch {
      // Channel may not support threads
    }
  }

  console.log(`\ndefaults:`);
  console.log(`  confidence_threshold: 0.5`);
  console.log(`  reconcile_lookback: 200`);
  console.log(`  reconcile_interval_hours: 6`);

  await shutdownClient();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
